name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-TigerLib:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle Wrapper
        run: chmod +x gradlew

      - name: Lint
        run: ./gradlew spotlessCheck

      - name: Javadoc
        run: ./gradlew javadoc

      - name: Assemble
        run: ./gradlew assemble

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew build
