name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  spotless:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Spotless
        run: |
          chmod +x gradlew
          ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Spotless
        run: |
          chmod +x gradlew
          ./gradlew build

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test project
        run: |
          chmod +x gradlew
          ./gradlew test
