name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - '**.gradle'
  pull_request:
      - created
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  spotless:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Spotless
        run: |
          chmod +x gradlew
          ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build -PenforceSpotless=false

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test
        run: |
          chmod +x gradlew
          ./gradlew test -PenforceSpotless=false
