name: CI/CD

# Run workflow when we create and publish a release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle Wrapper
        run: |
        chmod +x gradlew
        ./gradlew clean

      - name: Generate Javadocs
        run: ./gradlew javadoc -P"version=${{ github.event.release.tag_name }}"

      - name: Deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
